LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libopenaes
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_SRC_FILES := libopenaes.cpp
LOCAL_MULTILIB := both
LOCAL_MODULE_PATH_32 := $(TARGET_RECOVERY_ROOT_OUT)/system/lib
LOCAL_MODULE_PATH_64 := $(TARGET_RECOVERY_ROOT_OUT)/system/lib64
LOCAL_UNINSTALLABLE_MODULE := true
include $(BUILD_SHARED_LIBRARY)
